JAORMX/selinuxd

- pkg/daemon/action.go
- pkg/daemon/daemon.go
This defines an interface to do actions generically, and instead splits
the install and remove actions into their own objects. This keeps the
functions small and easier to understand.
> Split policy actions into objects

- .github/workflows/build_test.yaml
Adds a simple GH action that just runs make and make test. Uses an Ubuntu runner
because GH actions don't support fedora/centos. To work around that, the action
uses a centos:8 container. This means we can't test the policies themselves as
we'd need a SELinux-enabled container for that -- we can use a self-hosted
runner if we so desire later, though.
> Add github actions

- .github/workflows/build_test.yaml
By selectively enabling the only repository we need in addition to the
default set in order to install libsemanage-devel.
This also means the CI is faster as we have to fetch less metadata.
> Fix github actions

- pkg/daemon/daemon.go
filepath.Walk() calls walkFn() with info=nil when processing the root
directory. This was causing a crash.
> Fix panic on when walking the root dir

- cmd/daemon.go
- pkg/daemon/daemon.go
- pkg/daemon/daemon_test.go
- pkg/daemon/status_server.go
adds a new goroutine to the deamon that creates a socket that the deamon
listens on. There is an HTTP server listening on the socket that handles
a single path /policies and only handles HTTP GET requests. The answer
to that request is a JSON list of all the loaded policies as string,
similar to what a call to semanage -l would produce.
There is so far no access control on the socket except for the UNIX
permissions of the socket which are settable through command line
parameters.
> Provide a UNIX socket that allows listing policies

- .github/workflows/verify.yaml
- .golangci.yml
- Makefile
- cmd/daemon.go
- cmd/root.go
- pkg/daemon/action.go
- pkg/daemon/daemon.go
- pkg/daemon/daemon_test.go
- pkg/daemon/status_server.go
- pkg/semodule/interface.go
- pkg/semodule/semanage/semanage.go
- pkg/semodule/test/testhandler.go
- pkg/utils/utils.go
This introduces the `verify` target to the Makefile as well as a GH action that will run it.
It also fixes the warnings presented by the tool.
> Golangci lint: Introduce check and fix warnings

- cmd/common.go
- cmd/daemon.go
- cmd/oneshot.go
- pkg/daemon/action.go
- pkg/daemon/daemon.go
This allows us to do a oneshot pass at installing policies set up in the
/etc/selinux.d directory.
This will be useful for installing a bootstrap SELinux policy from an
initContainer to be used by a subsequent container.
> Implement oneshot command

- pkg/semodule/semanage/semanage.go
The semanage interface has a wrapped error for when commits fail. We
were wrapping the wrong error, instead we should wrap the "commit" one
to be able to correctly identify it if needed.
> semanage: Fix commit error wrapping

- cmd/daemon.go
- pkg/daemon/status_server.go
This adds a `--enable-profiling` flag to the daemon which can enable
some profiling endpoints in the status server similar to the defaults
that pprof gives.
> Optionally enable profiling

- Dockerfile
We were overwriting the `build` reference... we shouldn't name the
end-container image.
> Fix Dockerfile's name reference

- Makefile
- images/Dockerfile.centos
- images/Dockerfile.fedora
Since libsemanage isn't compatible between fedora and centos (which also
encompasses RHCOS and RHEL), we need to have separate images for
selinuxd to work on these distros.
I will eventually remove the top-level Dockerfile in favor of the ones
in the images directory.
> Enable fedora and centos container images builds

- cmd/daemon.go
- cmd/oneshot.go
- pkg/daemon/action.go
- pkg/daemon/daemon.go
- pkg/daemon/daemon_test.go
- pkg/daemon/status_server.go
- pkg/datastore/bbolt.go
- pkg/datastore/datastore.go
- pkg/datastore/datastore_test.go
- pkg/datastore/policystatus.go
- pkg/datastore/test.go
- pkg/semodule/interface.go
- pkg/semodule/semanage/semanage.go
- pkg/semodule/test/testhandler.go
- pkg/utils/utils.go
This exposes the Commit operation in the SeModule Handler code. It also
exposes the auto commit setting. What this means is that now we're able
to tell the library that we want to gather all modules and try to
install them all as part of the same transaction as opposed to doing it
per policy.
This is then used in the oneshot command, where the command will try to
do a single transaction to install all the policies, and if that fails
it'll go policy per policy installing them. This is meant to speed up
setting up initial policies.
Furthermore, this implements checksumming of all incoming policies.
The aforementioned checksum is stored in the datastore and checked on
every time we install a policy. With this, we are able to skip installing a
policy if it was previously installed and the …
> Enhance installation speed (theoretically)

- .github/workflows/build_image.yaml
This makes sure that new changes don't break the container builds.
Closes https://github.com/JAORMX/selinuxd/issues/30
> Add GH action to build Fedora and CentOS images

- .github/workflows/e2e.yml
- Makefile
- hack/ci/Vagrantfile
- hack/ci/daemon.sh
- hack/ci/e2e.sh
- hack/ci/logs.sh
- hack/ci/run.sh
This adds the basic setup to do e2e tests.
Note that e2e tests are still missing, but this gives us the ability to run them by:
* Adding an appropriate github actions workflow
* Adding a Vagrant configuration that sets up a fedora VM
* Running the daemon in a container
* fetching logs in the end of the run
> Add e2e test setup

- .github/workflows/e2e.yml
- hack/ci/Vagrantfile
- hack/ci/daemon.sh
In order to lock down the selinux deployment, this uses Udica to
generate an appropriate policy. This is eventually uploaded as an
artifact as part of the CI run.
> Use udica to generate selinux policy for selinuxd container

- .github/workflows/e2e.yml
This ensures that the workflow always tries to fetch logs, even if the
previous step failed. It also fetches the logs from the VM, which was
missing.
> e2e: Always fetch logs and fix log fetching

- Makefile
This allows us to get across manual CI retries if the download if the
image download has failed.
Props to @saschagrunert who originally authored this.
Co-Authored-By: Sascha Grunert <sgrunert@redhat.com>
> Automatically retry VM provisioning

- tests/e2e/e2e_test.go
This handles the use case of someone updating an erroneous policy.
> Add e2e test for policy update

- cmd/oneshot.go
- pkg/daemon/action.go
- pkg/daemon/daemon.go
- pkg/daemon/daemon_test.go
- pkg/daemon/dispatcher.go
- pkg/semodule/test/testhandler.go
- pkg/utils/utils.go
- tests/e2e/e2e_test.go
this ensures that selinuxd also takes sub-directories into account.
This ditches some previous code that would not trust the path... in this case
we have to trust the path from the fsnotify event as that will tell us the sub-directory.
> Add sub-directory tracking

- .github/workflows/e2e.yml
We're currently not able to check this as Udica doesn't generate the
policy files in order.
Related-bug: https://github.com/containers/udica/issues/84
Closes https://github.com/JAORMX/selinuxd/issues/56
> Remove check for selinux policy diff

- hack/ci/e2e-local.sh
This adds the option to the e2e-local.sh script.
I'ts enabled via the `E2E_SECURE` option
> Add option to run secure deployment locally

- security/selinuxd.cil
Instead of using the Fedora one which is not backwards compatible with
CentOS.
> Use CentOS CIL policy
